services:
  frontend:
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      JWT_SECRET: ${JWT_SECRET}
    env_file:
      - .env
volumes:
  postgres_data:
